modLoader="javafml"
loaderVersion="[36,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/ForgeEssentials/ForgeEssentials/issues"

[[mods]]
    modId="forgeessentials"
    version="${version}"
    displayName="${mod_name}"
    #updateJSONURL="https://change.me.example.invalid/updates.json" #optional
    displayURL="${mod_download}"
    logoFile="logo.png"
    credits="Thanks to everyone who has helped us so far."
    authors="AbrarSyed, luacs1998, olee, dries007, Malkierian, Spacebuilder2020, maximuslotro/MaximustheMiner, And a few others"
    description='''A suite of server mods for Minecraft Forge'''

[[dependencies.forgeessentials]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="SERVER"
[[dependencies.forgeessentials]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="SERVER"